#!/bin/bash
# Get snippets of html, store strings as env vars, HEAD and BODY
orig_pwd="$(readlink -f $PWD)"
export HOST="localhost"
export PORT="6777"
APIURL_JS="$(echo "const APIURL=\"http://$HOST:$PORT/api\"")"

cd client

cat<<EOF > globals.html
<script>
const APIURL="http://$HOST:$PORT/api"
</script>
EOF

export CSS="$(cat style.css tachyons.min.css)"
export HEAD="$(cat head.html cli.html terminal.html)"
export BODY="$(cat  globals.html body.html)"

cd $orig_pwd
mkdir -p public 
cat client/index.env | envsubst  > public/index.html
