#!/bin/bash
# Get snippets of html, store strings as env vars, HEAD and BODY
CLIENT_DIR="client"
export CSS="$(cd $CLIENT_DIR && cat style.css)"
export HEAD="$(cd $CLIENT_DIR && \
  cat head.html cli.html terminal.html)"
export BODY="$(cd $CLIENT_DIR && cat  body.html)"

# Write to public dir that is is served by node server.js
PUBLIC_DIR="public"
mkdir -p $PUBLIC_DIR 
cat $CLIENT_DIR/index.env | envsubst  > $PUBLIC_DIR/index.html
#!/bin/bash

oldpwd=$PWD
cd server
npm i
cd $oldpwd
